FROM archlinux/base
MAINTAINER byidi <sajot.vincent@gmail.com>

RUN ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime

RUN pacman -Syu --noconfirm nginx

RUN sed -i -E 's/^#(fr_FR.UTF-8 UTF-8)/\1/' /etc/locale.gen
RUN locale-gen

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
