version: '3'

services:
    flask-nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        container_name: flask-nginx
        ports:
            - 80:80
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - ./log:/etc/nginx/log
        restart: unless-stopped

    #flask-db:
    #   image: mariadb:latest
    #    container_name: flask-db
     #   volumes:
      #      - flask-db-data:/var/mysql
     #   environment:
      #      MYSQL_ROOT_PASSWORD: azer
      #      MYSQL_DATABASE: flaskdb
       #     MYSQL_USER: flaskuser
        #    MYSQL_PASSWORD: flaskpasswd
       # restart: unless-stopped

    flask-app:
        build:
            context: .
            dockerfile: Dockerfile-flask
        container_name: flask-app
        ports:
            - 5000
        volumes:
            - ../app:/app
        environment:
            - FLASK_DEBUG=1
            - FLASK_ENV=development
            - FLASK_APP=/app
        command: flask run --host=0.0.0.0
        restart: unless-stopped
